"""empty message

Revision ID: d3184fd3bf8c
Revises: None
Create Date: 2017-01-22 16:53:17.953835

"""

# revision identifiers, used by Alembic.
revision = 'd3184fd3bf8c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('current_product', sa.String(length=4), nullable=True),
    sa.Column('count_products', sa.String(length=4), nullable=True),
    sa.Column('page_number', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('subname', sa.String(length=50), nullable=True),
    sa.Column('images', sa.String(length=550), nullable=True),
    sa.Column('prices', sa.String(length=250), nullable=True),
    sa.Column('colors_imgs', sa.String(length=250), nullable=True),
    sa.Column('colors_links', sa.String(length=250), nullable=True),
    sa.Column('sizes', sa.String(length=250), nullable=True),
    sa.Column('params', sa.String(length=250), nullable=True),
    sa.Column('views', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('parse')
    # ### end Alembic commands ###
